default_platform(:ios)

platform :ios do
  lane :certificates do
    app_store_connect_api_key(
	key_filepath: "./AuthKey_KVXJ2VBJXD.p8",
	duration: 1200, 
    )
    team_id("ZWXN4J2VCP")
    match(type: "appstore", readonly:false)
  end

  lane :upload_to_test_flight do
    certificates
    increment_build_number
    build_ios_app
    upload_to_testflight(skip_submission: false)
  end
end
