default_platform(:ios)

platform :ios do
  desc "Load ASC API Key information to use in subsequent lanes"
  lane :load_asc_api_key do
    setup_ci
    app_store_connect_api_key(
     key_id: ENV["ASC_KEY_ID"],
     issuer_id: ENV["ASC_ISSUER_ID"],
     key_content: ENV["ASC_KEY"],
     is_key_content_base64: true,
     in_house: false 
    )
    team_id(ENV["TEAM_ID"])
    match(
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      type: "appstore", 
      readonly:true
    )
  end

  lane :upload_to_test_flight do
    load_asc_api_key
    increment_build_number
    build_ios_app
    upload_to_testflight(skip_submission: true, skip_waiting_for_build_processing: true)
  end
end
