default_platform(:android)

platform :android do
  desc "Upload build to internal test"
  lane :test do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: "internal")
  end
end
