name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  deploy:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./iosHavePawsApp
    steps:
      - uses: actions/checkout@v3

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          
      - name: Install bundler
        run: gem install bundler:1.17.2
        
      - name: Setup Fastlane
        run: bundle install   
        
      - name: Build & deploy iOS release
        run: bundle exec fastlane ios upload_to_test_flight
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY: ${{ secrets.ASC_KEY }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          
